### PR TITLE
Load cl-lib for using loop macro

### PR DESCRIPTION
**Pull request by syohex**

### CODE REVIEW

**Comment by sshaw** [comment]
Hi, thanks for the pull request, but one question RE melpa/melpa#4440. How should I deal with the autoloading of these functions? Via:

```
;;;###autoload (autoload 'copy-as-format-slack "copy-as-format")
;;;###autoload (autoload 'copy-as-format-github "copy-as-format")
;; ...
```
?

**Comment by syohex** [comment]
Define functions as below instead of defining them at runtime.

```lisp
;;;###autoload
(defun copy-as-format-github ()
  (interactive)
  (setq copy-as-format-default "github")
  (copy-as-format))
```

**Comment by sshaw** [comment]
> Define functions as below instead of defining them at runtime.

What's wrong with keeping them dynamic and adding more explicit autoload definitions?

Thanks

**Comment by syohex** [comment]
Ah, sorry. Both are same except 4th argument of autoload. You should set 4th argument which means that functions is an interactive command.

```
;;;###autoload (autoload 'copy-as-format-bitbucket "copy-as-format" nil t)
```

**Pull request merged**
